# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'KernelGenerator.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(787, 708)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(30, 170, 171, 21))
        self.label.setScaledContents(False)
        self.radioButton_freq_5 = QRadioButton(self.centralwidget)
        self.radioButton_freq_5.setObjectName(u"radioButton_freq_5")
        self.radioButton_freq_5.setGeometry(QRect(220, 170, 51, 23))
        self.radioButton_freq_5.setChecked(True)
        self.radioButton_freq_17 = QRadioButton(self.centralwidget)
        self.radioButton_freq_17.setObjectName(u"radioButton_freq_17")
        self.radioButton_freq_17.setGeometry(QRect(340, 170, 71, 23))
        self.radioButton_freq_40 = QRadioButton(self.centralwidget)
        self.radioButton_freq_40.setObjectName(u"radioButton_freq_40")
        self.radioButton_freq_40.setGeometry(QRect(470, 170, 71, 23))
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(30, 100, 161, 17))
        self.lumination_edit_min = QPlainTextEdit(self.centralwidget)
        self.lumination_edit_min.setObjectName(u"lumination_edit_min")
        self.lumination_edit_min.setGeometry(QRect(220, 100, 71, 31))
        self.lumination_edit_min.setInputMethodHints(Qt.ImhDigitsOnly)
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(220, 140, 81, 17))
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(340, 140, 81, 17))
        self.lumination_edit_max = QPlainTextEdit(self.centralwidget)
        self.lumination_edit_max.setObjectName(u"lumination_edit_max")
        self.lumination_edit_max.setGeometry(QRect(340, 100, 71, 31))
        self.lumination_edit_max.setInputMethodHints(Qt.ImhDigitsOnly)
        self.lumination_edit_max.setLineWrapMode(QPlainTextEdit.WidgetWidth)
        self.lumination_edit_max.setCenterOnScroll(False)
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(30, 240, 151, 17))
        self.checkBox_object_1500 = QCheckBox(self.centralwidget)
        self.checkBox_object_1500.setObjectName(u"checkBox_object_1500")
        self.checkBox_object_1500.setGeometry(QRect(220, 240, 71, 23))
        self.checkBox_object_2750 = QCheckBox(self.centralwidget)
        self.checkBox_object_2750.setObjectName(u"checkBox_object_2750")
        self.checkBox_object_2750.setGeometry(QRect(340, 240, 71, 23))
        self.checkBox_object_5000 = QCheckBox(self.centralwidget)
        self.checkBox_object_5000.setObjectName(u"checkBox_object_5000")
        self.checkBox_object_5000.setGeometry(QRect(460, 240, 71, 23))
        self.checkBox_stellar_8 = QCheckBox(self.centralwidget)
        self.checkBox_stellar_8.setObjectName(u"checkBox_stellar_8")
        self.checkBox_stellar_8.setGeometry(QRect(460, 310, 81, 23))
        self.checkBox_stellar_1 = QCheckBox(self.centralwidget)
        self.checkBox_stellar_1.setObjectName(u"checkBox_stellar_1")
        self.checkBox_stellar_1.setGeometry(QRect(220, 310, 81, 23))
        self.checkBox_stellar_3 = QCheckBox(self.centralwidget)
        self.checkBox_stellar_3.setObjectName(u"checkBox_stellar_3")
        self.checkBox_stellar_3.setGeometry(QRect(340, 310, 81, 23))
        self.label_6 = QLabel(self.centralwidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(30, 310, 151, 17))
        self.label_7 = QLabel(self.centralwidget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(30, 370, 151, 31))
        self.checkBox_impact_0 = QCheckBox(self.centralwidget)
        self.checkBox_impact_0.setObjectName(u"checkBox_impact_0")
        self.checkBox_impact_0.setGeometry(QRect(220, 380, 51, 23))
        self.checkBox_impact_half_radius = QCheckBox(self.centralwidget)
        self.checkBox_impact_half_radius.setObjectName(u"checkBox_impact_half_radius")
        self.checkBox_impact_half_radius.setGeometry(QRect(340, 370, 101, 41))
        self.checkBox_impact_radius = QCheckBox(self.centralwidget)
        self.checkBox_impact_radius.setObjectName(u"checkBox_impact_radius")
        self.checkBox_impact_radius.setGeometry(QRect(460, 360, 121, 61))
        self.checkBox_shift_25 = QCheckBox(self.centralwidget)
        self.checkBox_shift_25.setObjectName(u"checkBox_shift_25")
        self.checkBox_shift_25.setGeometry(QRect(460, 450, 111, 23))
        self.checkBox_shift_negative_25 = QCheckBox(self.centralwidget)
        self.checkBox_shift_negative_25.setObjectName(u"checkBox_shift_negative_25")
        self.checkBox_shift_negative_25.setGeometry(QRect(220, 450, 111, 23))
        self.checkBox_shift_0 = QCheckBox(self.centralwidget)
        self.checkBox_shift_0.setObjectName(u"checkBox_shift_0")
        self.checkBox_shift_0.setGeometry(QRect(340, 450, 91, 23))
        self.label_8 = QLabel(self.centralwidget)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(30, 450, 171, 17))
        self.checkBox_shift_5 = QCheckBox(self.centralwidget)
        self.checkBox_shift_5.setObjectName(u"checkBox_shift_5")
        self.checkBox_shift_5.setGeometry(QRect(580, 450, 101, 23))
        self.label_9 = QLabel(self.centralwidget)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(30, 20, 121, 17))
        self.label_10 = QLabel(self.centralwidget)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(230, 60, 41, 17))
        self.distance_edit = QPlainTextEdit(self.centralwidget)
        self.distance_edit.setObjectName(u"distance_edit")
        self.distance_edit.setGeometry(QRect(220, 20, 71, 31))
        self.distance_edit.setInputMethodHints(Qt.ImhDigitsOnly)
        self.label_11 = QLabel(self.centralwidget)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(30, 520, 121, 17))
        self.file_name_edit = QPlainTextEdit(self.centralwidget)
        self.file_name_edit.setObjectName(u"file_name_edit")
        self.file_name_edit.setGeometry(QRect(220, 520, 161, 31))
        self.file_name_edit.setInputMethodHints(Qt.ImhMultiLine)
        self.file_name_edit.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.pushButton_generate_kernels = QPushButton(self.centralwidget)
        self.pushButton_generate_kernels.setObjectName(u"pushButton_generate_kernels")
        self.pushButton_generate_kernels.setGeometry(QRect(220, 630, 121, 51))
        self.pushButton_reset = QPushButton(self.centralwidget)
        self.pushButton_reset.setObjectName(u"pushButton_reset")
        self.pushButton_reset.setGeometry(QRect(380, 630, 121, 51))
        self.progressBar = QProgressBar(self.centralwidget)
        self.progressBar.setObjectName(u"progressBar")
        self.progressBar.setGeometry(QRect(220, 570, 301, 23))
        self.progressBar.setValue(0)
        self.label_12 = QLabel(self.centralwidget)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(30, 570, 121, 17))
        self.progress_Label = QLabel(self.centralwidget)
        self.progress_Label.setObjectName(u"progress_Label")
        self.progress_Label.setGeometry(QRect(530, 570, 41, 17))
        self.progress_Label.setInputMethodHints(Qt.ImhMultiLine)
        self.edit_shift_adjustment = QPlainTextEdit(self.centralwidget)
        self.edit_shift_adjustment.setObjectName(u"edit_shift_adjustment")
        self.edit_shift_adjustment.setGeometry(QRect(690, 450, 71, 31))
        self.edit_shift_adjustment.setInputMethodHints(Qt.ImhMultiLine)
        self.edit_shift_adjustment.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.edit_impact_factor = QPlainTextEdit(self.centralwidget)
        self.edit_impact_factor.setObjectName(u"edit_impact_factor")
        self.edit_impact_factor.setGeometry(QRect(690, 380, 71, 31))
        self.edit_impact_factor.setInputMethodHints(Qt.ImhMultiLine)
        self.edit_impact_factor.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.edit_stellar_diameter = QPlainTextEdit(self.centralwidget)
        self.edit_stellar_diameter.setObjectName(u"edit_stellar_diameter")
        self.edit_stellar_diameter.setGeometry(QRect(690, 310, 71, 31))
        self.edit_stellar_diameter.setInputMethodHints(Qt.ImhMultiLine)
        self.edit_stellar_diameter.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.edit_object_diameter = QPlainTextEdit(self.centralwidget)
        self.edit_object_diameter.setObjectName(u"edit_object_diameter")
        self.edit_object_diameter.setGeometry(QRect(690, 240, 71, 31))
        self.edit_object_diameter.setInputMethodHints(Qt.ImhMultiLine)
        self.edit_object_diameter.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.edit_frequency = QPlainTextEdit(self.centralwidget)
        self.edit_frequency.setObjectName(u"edit_frequency")
        self.edit_frequency.setGeometry(QRect(690, 170, 71, 31))
        self.edit_frequency.setInputMethodHints(Qt.ImhMultiLine)
        self.edit_frequency.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.label_13 = QLabel(self.centralwidget)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(690, 490, 61, 17))
        self.label_14 = QLabel(self.centralwidget)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(710, 420, 31, 17))
        self.label_15 = QLabel(self.centralwidget)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(700, 350, 61, 17))
        self.label_16 = QLabel(self.centralwidget)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(690, 280, 81, 17))
        self.label_17 = QLabel(self.centralwidget)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(700, 210, 41, 17))
        #MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Kernel Generator GUI", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Sampling Frequency(m):", None))
        self.radioButton_freq_5.setText(QCoreApplication.translate("MainWindow", u"5 Hz", None))
        self.radioButton_freq_17.setText(QCoreApplication.translate("MainWindow", u"17 Hz", None))
        self.radioButton_freq_40.setText(QCoreApplication.translate("MainWindow", u"40 Hz", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Wavelength Bands(Nm):", None))
        self.lumination_edit_min.setPlaceholderText(QCoreApplication.translate("MainWindow", u"400", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Min(in Nm)", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Max(in Nm)", None))
        self.lumination_edit_max.setPlaceholderText(QCoreApplication.translate("MainWindow", u"700", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Object Diameter(m):", None))
        self.checkBox_object_1500.setText(QCoreApplication.translate("MainWindow", u"1500 m", None))
        self.checkBox_object_2750.setText(QCoreApplication.translate("MainWindow", u"2750 m", None))
        self.checkBox_object_5000.setText(QCoreApplication.translate("MainWindow", u"5000 m", None))
        self.checkBox_stellar_8.setText(QCoreApplication.translate("MainWindow", u"0.08 mas", None))
        self.checkBox_stellar_1.setText(QCoreApplication.translate("MainWindow", u"0.01 mas", None))
        self.checkBox_stellar_3.setText(QCoreApplication.translate("MainWindow", u"0.03 mas", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Stellar Diameter(mas):", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Impact Factor \n"
"(units of radius):", None))
        self.checkBox_impact_0.setText(QCoreApplication.translate("MainWindow", u"0.0", None))
        self.checkBox_impact_half_radius.setText(QCoreApplication.translate("MainWindow", u"Half Object \n"
"Radius", None))
        self.checkBox_impact_radius.setText(QCoreApplication.translate("MainWindow", u"Object Radius", None))
        self.checkBox_shift_25.setText(QCoreApplication.translate("MainWindow", u"0.25 frames", None))
        self.checkBox_shift_negative_25.setText(QCoreApplication.translate("MainWindow", u"- 0.25 frames", None))
        self.checkBox_shift_0.setText(QCoreApplication.translate("MainWindow", u"0 frames", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Shift Adjustment(frame):", None))
        self.checkBox_shift_5.setText(QCoreApplication.translate("MainWindow", u"0.5 frames", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Distance(au):", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"(in au)", None))
        self.distance_edit.setPlaceholderText(QCoreApplication.translate("MainWindow", u"40", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"File Name(.txt):", None))
        self.file_name_edit.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Kernel.txt", None))
        self.pushButton_generate_kernels.setText(QCoreApplication.translate("MainWindow", u"Generate \n"
" Kernels", None))
        self.pushButton_reset.setText(QCoreApplication.translate("MainWindow", u"Reset All", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"Progress Bar", None))
        self.progress_Label.setText("")
        self.edit_shift_adjustment.setPlaceholderText(QCoreApplication.translate("MainWindow", u"frames", None))
        self.edit_impact_factor.setPlaceholderText(QCoreApplication.translate("MainWindow", u"m", None))
        self.edit_stellar_diameter.setPlaceholderText(QCoreApplication.translate("MainWindow", u"mas", None))
        self.edit_object_diameter.setPlaceholderText(QCoreApplication.translate("MainWindow", u"m", None))
        self.edit_frequency.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Hz", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"- 0.5 - 0.5", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"0 - 1", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"0.001 - 1", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"10 - 10,000", None))
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"5 - 80", None))
    # retranslateUi

